// Repositories/CustomerRepository.cs
using System;
using System.Linq;
using dotnetapp.Models;
using dotnetapp.Data;  // Assuming ApplicationDbContext is in the Data namespace

public class CustomerRepository
{
    private readonly ApplicationDbContext _context;

    public CustomerRepository(ApplicationDbContext context)
    {
        _context = context;
    }

    public Customer RegisterCustomer(Customer customer)
    {
        // Assuming CustomerId is generated by the database
        _context.Customers.Add(customer);
        _context.SaveChanges();

        return customer;
    }

    public Customer GetCustomerById(long customerId)
    {
        return _context.Customers.FirstOrDefault(c => c.CustomerId == customerId);
    }
}
